roadmap page mobile responsive
defientco/CRE8ORS-UI pull request #25
Opened 2023-06-21 00:22 UTC by towardsnewtech

2023-06-21 21:22 UTC, SweetmanTech approved these changes
looks good to ship 🚢 

gonna review UX now

2023-06-21 21:22 UTC, SweetmanTech commented on components/RoadmapPage/RoadmapPage.tsx
> +      backImg: "/assets/Roadmap/build.svg",
optional: would be nice to split this out into it's own`.json` file to not clutter up the HTML.

love this architecture you've built. 🏗️ 

very easy to modify / update over time. ✏️

2023-06-22 16:37 UTC, SweetmanTech approved these changes
small comments, overall looking good ✅

2023-06-22 16:37 UTC, SweetmanTech commented on components/RoadmapPage/RoadmapPage.tsx
> +  let offset
can you move this declaration inside your `useEffect` hook?

It's only being used there, correct?

2023-06-22 16:37 UTC, SweetmanTech commented on components/RoadmapPage/data.json
> +]
💯

2023-06-22 16:37 UTC, sweetmantech commented on components/RoadmapPage/data.json
> +    "text": ""
missing `text` for the remaining boxes

2023-06-23 02:30 UTC, SweetmanTech requested changes
remove code unrelated to `Roadmap Page`
- remove Claim Page components 🚮

2023-06-23 02:30 UTC, SweetmanTech commented on components/ClaimPage/ClaimPage.tsx
> +const ClaimPage = () => {
same feedback as Claim Page

Why is Claim Page code in your pull request for Roadmap Page?

blocker: please remove Claim Page code from your Roadmap Page pull request 🚮

2023-06-23 02:30 UTC, SweetmanTech commented on components/RoadmapPage/Stage.tsx
> +    </div>
this component for `<Stage />` is starting to get a little big & messy, would you agree?

Maybe we can make this more readable by making some reusable `child` components? 💭

2023-06-23 02:30 UTC, SweetmanTech commented on components/RoadmapPage/Stage.tsx
> +    </div>
non-blocking, just a thought

2023-06-23 02:30 UTC, SweetmanTech commented on pages/claim/index.tsx
> +const Claim = () => <ClaimPage />
please remove all files unrelated to `Roadmap Page` 🚮

2023-06-23 02:45 UTC, SweetmanTech approved these changes
ship it 🚢

2023-06-23 14:43 UTC, merged